# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_auto_20181102_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='directoryPath',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='timeTagged',
            field=models.DateTimeField(default=None, verbose_name='date tagged'),
        ),
    ]
