# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 23:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiApp', '0007_auto_20181103_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='timeTagged',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 23, 0, 11, 532399, tzinfo=utc), verbose_name='date tagged'),
        ),
    ]
