# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 03:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_auto_20181111_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetrel',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='targetrel',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='timeTagged',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 3, 58, 21, 966331, tzinfo=utc), verbose_name='date tagged'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
