# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('hsClass', models.IntegerField(default=0)),
                ('directoryPath', models.CharField(max_length=200)),
                ('timeTagged', models.DateTimeField(verbose_name='date tagged')),
                ('numOfTags', models.IntegerField(default=0)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='targetrel',
            name='tagger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relForward', to='apiApp.User'),
        ),
        migrations.AddField(
            model_name='targetrel',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relBackward', to='apiApp.User'),
        ),
    ]
