# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_auto_20181103_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='aliveStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='targetrel',
            old_name='aliveStatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='player',
            name='timeTagged',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 19, 17, 16, 302304, tzinfo=utc), verbose_name='date tagged'),
        ),
    ]
